filter:
    excluded_paths:
        - 'Configuration/*'
        - 'Packages/Framework/*'
        - 'Packages/Libraries/*'
        - 'Packages/Application/Roketi.Panel/Classes/Service/IdnaConvertOriginal.php'

tools:
    external_code_coverage:
        enabled: true
        timeout: 900

    php_cpd:
        enabled: true

    php_code_sniffer:
        enabled: true
        config:
            standard: TYPO3Flow

    php_cs_fixer:
        enabled: true
        config:
          level: psr1

    php_hhvm:
        enabled: true

    php_mess_detector:
        enabled: true

    php_pdepend:
        enabled: true

    php_analyzer:
        enabled: true

    sensiolabs_security_checker: true